kind: Secret
apiVersion: v1
metadata:
  name: quay-auth
  namespace: liran
  annotations:
    tekton.dev/docker-0: 'https://quay.io'
data:
  .dockerconfigjson: <secret>
type: kubernetes.io/dockerconfigjson
