schemaVersion: 2.3.0
metadata:
    name: aib-devspaces
    tags:
        - Jumpstarter
        - Automotive
    language: C
projects:
    - name: aib-devspaces
      git:
          remotes:
              origin: https://github.com/rh-sdv-cloud-incubator/aib-devspaces.git
components:
    - name: runtime
      container:
          image: quay.io/rh-sdv-cloud/aib-base-dev:latest
          mountSources: true
          args: ["tail", "-f", "/dev/null"]
          env:
              - name: KUBEDOCK_ENABLED
                value: "true"
              - name: KUBECONFIG
                value: "/home/user/.kube/config"
              - name: JMP_CLIENT_CONFIG_HOME
                value: "/home/user/.jumpstarter"

commands:
    - id: build-container
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-container

    - id: build-app
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-app

    - id: clean
      exec:
          component: runtime
          commandLine: make -f Makefile.dev clean

    - id: set-app-image
      exec:
          component: runtime
          commandLine: make -f Makefile.dev set-app-image

    - id: build-image-ti
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-image-ti

    - id: flash-image
      exec:
          component: runtime
          commandLine: make -f Makefile.dev flash-image

    - id: test-sample-apps
      exec:
          component: runtime
          commandLine: make -f Makefile.dev test-sample-apps

    - id: publish-image-reg
      exec:
          component: runtime
          commandLine: make -f Makefile.dev publish-image-reg

    - id: deploy-changes
      exec:
          component: runtime
          commandLine: make -f Makefile.dev deploy-changes
          group:
              kind: run
              isDefault: false

    - id: build-all
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-all
          group:
              kind: build
              isDefault: true
