# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bzlotnik/development/automotive/aib-devspaces

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bzlotnik/development/automotive/aib-devspaces

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"bin\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bzlotnik/development/automotive/aib-devspaces/CMakeFiles /home/bzlotnik/development/automotive/aib-devspaces//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bzlotnik/development/automotive/aib-devspaces/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named radio-service

# Build rule for target.
radio-service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 radio-service
.PHONY : radio-service

# fast build rule for target.
radio-service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/build
.PHONY : radio-service/fast

#=============================================================================
# Target rules for targets named radio-client

# Build rule for target.
radio-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 radio-client
.PHONY : radio-client

# fast build rule for target.
radio-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-client.dir/build.make CMakeFiles/radio-client.dir/build
.PHONY : radio-client/fast

#=============================================================================
# Target rules for targets named engine-service

# Build rule for target.
engine-service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-service
.PHONY : engine-service

# fast build rule for target.
engine-service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-service.dir/build.make CMakeFiles/engine-service.dir/build
.PHONY : engine-service/fast

engine-service.o: engine-service.cpp.o
.PHONY : engine-service.o

# target to build an object file
engine-service.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-service.dir/build.make CMakeFiles/engine-service.dir/engine-service.cpp.o
.PHONY : engine-service.cpp.o

engine-service.i: engine-service.cpp.i
.PHONY : engine-service.i

# target to preprocess a source file
engine-service.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-service.dir/build.make CMakeFiles/engine-service.dir/engine-service.cpp.i
.PHONY : engine-service.cpp.i

engine-service.s: engine-service.cpp.s
.PHONY : engine-service.s

# target to generate assembly for a file
engine-service.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-service.dir/build.make CMakeFiles/engine-service.dir/engine-service.cpp.s
.PHONY : engine-service.cpp.s

radio-client.o: radio-client.cpp.o
.PHONY : radio-client.o

# target to build an object file
radio-client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-client.dir/build.make CMakeFiles/radio-client.dir/radio-client.cpp.o
.PHONY : radio-client.cpp.o

radio-client.i: radio-client.cpp.i
.PHONY : radio-client.i

# target to preprocess a source file
radio-client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-client.dir/build.make CMakeFiles/radio-client.dir/radio-client.cpp.i
.PHONY : radio-client.cpp.i

radio-client.s: radio-client.cpp.s
.PHONY : radio-client.s

# target to generate assembly for a file
radio-client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-client.dir/build.make CMakeFiles/radio-client.dir/radio-client.cpp.s
.PHONY : radio-client.cpp.s

radio-service.o: radio-service.cpp.o
.PHONY : radio-service.o

# target to build an object file
radio-service.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/radio-service.cpp.o
.PHONY : radio-service.cpp.o

radio-service.i: radio-service.cpp.i
.PHONY : radio-service.i

# target to preprocess a source file
radio-service.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/radio-service.cpp.i
.PHONY : radio-service.cpp.i

radio-service.s: radio-service.cpp.s
.PHONY : radio-service.s

# target to generate assembly for a file
radio-service.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/radio-service.cpp.s
.PHONY : radio-service.cpp.s

radio-stations.o: radio-stations.cpp.o
.PHONY : radio-stations.o

# target to build an object file
radio-stations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/radio-stations.cpp.o
.PHONY : radio-stations.cpp.o

radio-stations.i: radio-stations.cpp.i
.PHONY : radio-stations.i

# target to preprocess a source file
radio-stations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/radio-stations.cpp.i
.PHONY : radio-stations.cpp.i

radio-stations.s: radio-stations.cpp.s
.PHONY : radio-stations.s

# target to generate assembly for a file
radio-stations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radio-service.dir/build.make CMakeFiles/radio-service.dir/radio-stations.cpp.s
.PHONY : radio-stations.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... engine-service"
	@echo "... radio-client"
	@echo "... radio-service"
	@echo "... engine-service.o"
	@echo "... engine-service.i"
	@echo "... engine-service.s"
	@echo "... radio-client.o"
	@echo "... radio-client.i"
	@echo "... radio-client.s"
	@echo "... radio-service.o"
	@echo "... radio-service.i"
	@echo "... radio-service.s"
	@echo "... radio-stations.o"
	@echo "... radio-stations.i"
	@echo "... radio-stations.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

